theme: jekyll-theme-minimal
title: Statistical guideline for a financially successful movie taking inflation into consideration
description: Statistical guideline
show_downloads: True
navigation:
  - title: Statistical guideline for a financially successful movie
    url: starting_website
