theme: jekyll-theme-minimal
title: Statistical guideline for a financially successful movie taking inflation into consideration
description: Everyone loves movies!
show_downloads: True
navigation:
  - title: Starting_website
    url: starting_website
